### PR TITLE
dep-status: minimal change to use `dep-status` "Type"

### PR DESCRIPTION
**Pull request by zellyn**

### CODE REVIEW

**Comment by sdboyer** [comment]
seems good 😄

**Comment by sdboyer** [comment]
didn't seem to do the trick, though :(

**Comment by zellyn** [comment]
Weird… With `hugo server --buildDrafts` running locally, it totally works.

**Comment by sdboyer** [comment]
it might be a relic of how i have caddy set up.

in any case, this is a helpful bump in the right direction. makes it easy to investigate more myself :)

**Pull request merged**
